import type { PokemonGameOption } from '../types/game'

export const POKEMON_GAME_OPTIONS: PokemonGameOption[] = [
  { value: 'yellow', label: 'Jaune' },
  { value: 'red', label: 'Rouge' },
  { value: 'blue', label: 'Bleu' },
  { value: 'gold', label: 'Or' },
  { value: 'silver', label: 'Argent' },
  { value: 'crystal', label: 'Cristal' },
  { value: 'ruby', label: 'Rubis' },
  { value: 'sapphire', label: 'Saphir' },
  { value: 'emerald', label: 'Emeraude' },
  { value: 'colosseum', label: 'Colosseum' },
  { value: 'xd', label: 'XD' },
  { value: 'fire-red', label: 'Rouge Feu' },
  { value: 'leaf-green', label: 'Vert Feuille' },
  { value: 'diamond', label: 'Diamant' },
  { value: 'pearl', label: 'Perle' },
  { value: 'platinum', label: 'Platine' },
  { value: 'heart-gold', label: 'HeartGold' },
  { value: 'soul-silver', label: 'SoulSilver' },
  { value: 'black', label: 'Noir' },
  { value: 'white', label: 'Blanc' },
  { value: 'black-2', label: 'Noir 2' },
  { value: 'white-2', label: 'Blanc 2' },
  { value: 'x', label: 'X' },
  { value: 'y', label: 'Y' },
  { value: 'sun', label: 'Soleil' },
  { value: 'moon', label: 'Lune' },
  { value: 'ultra-sun', label: 'Ultra-Soleil' },
  { value: 'ultra-moon', label: 'Ultra-Lune' },
  { value: 'sword', label: 'Epée' },
  { value: 'shield', label: 'Bouclier' },
  { value: 'scarlet', label: 'Ecarlate' },
  { value: 'violet', label: 'Violet' }
]
